import React from "react";
import "./Offer.css";
import Tile from "../Tile/Tile";
// import chiru from "./../../assets/images/chiru.jpg";
// import endo from "./../../assets/images/endo.jpg";
// import higienizacja from "./../../assets/images/higienizacja.jpg";
// import ortho from "./../../assets/images/ortho.jpg";
// import protetyka from "./../../assets/images/protetyka.jpg";
// import wybielanie from "./../../assets/images/wybielanie.jpg";
// import xray from "./../../assets/images/xray.jpg";
import zacho from "./../../assets/images/zacho.jpg";

const tilesData = [
  {
    title: "IMPLANTOLOGIA",
    description: "Nowoczesne implanty zębowe.",
    modalText:
      "Implantologia to dziedzina stomatologii, która pozwala przywrócić nie tylko pełen uśmiech, ale także komfort codziennego życia. Dzięki nowoczesnym rozwiązaniom możliwe jest uzupełnienie braków w uzębieniu w sposób trwały i estetyczny, bez konieczności korzystania z ruchomych protez. Implant zębowy to niewielka śruba wykonana z tytanu, materiału biokompatybilnego, który doskonale integruje się z kością. Umieszcza się go w miejscu utraconego zęba, gdzie pełni funkcję jego korzenia. Na implancie mocuje się koronę, która wiernie imituje naturalny ząb pod względem wyglądu i funkcji. Dzięki temu możesz cieszyć się pewnością siebie, swobodnie rozmawiać, jeść i uśmiechać się, jakbyś nigdy nie stracił zęba. Proces leczenia implantologicznego jest starannie zaplanowany i przebiega etapowo. Wszystko zaczyna się od konsultacji, podczas której lekarz ocenia stan jamy ustnej, wykonuje niezbędne badania diagnostyczne i opracowuje indywidualny plan leczenia. Sam zabieg wszczepienia implantu jest bezpieczny, przeprowadzany w znieczuleniu miejscowym i trwa zazwyczaj kilkadziesiąt minut. Po okresie gojenia, który pozwala implantowi na zintegrowanie się z kością, przechodzi się do etapu odbudowy protetycznej – na implancie mocuje się koronę, most lub protezę. Implanty zębowe to rozwiązanie nie tylko estetyczne, ale i zdrowotne. Brak zęba może prowadzić do zaniku kości w miejscu ubytku, co wpływa na strukturę twarzy i funkcjonowanie całej jamy ustnej. Dzięki implantom proces ten zostaje zahamowany, a Twój uśmiech odzyskuje naturalny wygląd. Jeśli szukasz trwałego rozwiązania, które przywróci Ci radość z jedzenia, mówienia i uśmiechania się, implantologia jest odpowiedzią. To inwestycja w zdrowie, pewność siebie i komfort na długie lata. Umów się na konsultację i przekonaj się, jak możemy pomóc Ci odzyskać uśmiech, na który zasługujesz.",
    backgroundImagePath: `url(${require("./../../assets/images/zacho.jpg")})`,
  },
  {
    title: "ENDODONCJA",
    description: "Zabiegi leczenia kanałowego z użyciem mikroskopu.",
    modalText:
      "Endodoncja - precyzyjne leczenie kanałowe. Endodoncja, znana również jako leczenie kanałowe, to dziedzina stomatologii zajmująca się leczeniem chorób miazgi zęba oraz tkanek okołowierzchołkowych. Dzięki nowoczesnym technikom i precyzyjnym narzędziom możliwe jest uratowanie zębów, które dawniej byłyby przeznaczone do usunięcia. Leczenie endodontyczne to szansa na zachowanie naturalnego zęba i przywrócenie jego pełnej funkcjonalności. Leczenie kanałowe polega na dokładnym oczyszczeniu wnętrza zęba, usunięciu zainfekowanej miazgi, a następnie wypełnieniu kanałów specjalnym materiałem, który zapobiega dalszym infekcjom. Zabieg przeprowadzany jest z wykorzystaniem mikroskopu stomatologicznego, co pozwala na niezwykłą precyzję i dokładność. Nawet w przypadku skomplikowanych anatomii korzeni, mikroskop umożliwia leczenie, które wcześniej było niemożliwe. Jednym z głównych celów endodoncji jest eliminacja bólu. Infekcje miazgi zęba często wiążą się z silnym bólem i dyskomfortem. Po leczeniu ból ustępuje, a pacjent odzyskuje pełen komfort. Co więcej, zachowanie naturalnego zęba jest zawsze lepszym rozwiązaniem niż jego usunięcie – pozwala uniknąć konieczności stosowania mostów, implantów lub protez. Proces leczenia rozpoczyna się od szczegółowej diagnostyki, która obejmuje zdjęcia RTG oraz ocenę stanu zęba. Następnie lekarz przeprowadza leczenie w znieczuleniu miejscowym, co sprawia, że zabieg jest bezbolesny i komfortowy. W przypadku bardziej zaawansowanych zmian, leczenie może wymagać kilku wizyt, ale efektem końcowym jest wyleczony ząb, który może służyć przez wiele lat. Endodoncja to rozwiązanie dla osób, które chcą zachować swoje naturalne zęby, unikając ekstrakcji i jej konsekwencji. Dzięki nowoczesnym metodom, leczenie kanałowe jest szybkie, bezpieczne i skuteczne. Jeśli odczuwasz ból zęba lub zauważyłeś obrzęk, zgłoś się na konsultację. Pomożemy Ci znaleźć najlepsze rozwiązanie i zadbać o zdrowie Twoich zębów. Twój komfort i uśmiech są dla nas najważniejsze!",
  },
  {
    title: "CHIRURGIA",
    description: "Profesjonalne zabiegi chirurgiczne w jamie ustnej.",
    modalText:
      " Chirurgia stomatologiczna to kompleksowe rozwiązania dla Twojego zdrowia Chirurgia stomatologiczna to obszar stomatologii, który zajmuje się bardziej zaawansowanymi procedurami w jamie ustnej. To nie tylko ekstrakcje zębów, ale także szeroki wachlarz zabiegów, które pozwalają rozwiązać poważniejsze problemy zdrowotne i estetyczne. Dzięki nowoczesnym technologiom i precyzyjnym metodom, nawet skomplikowane zabiegi można przeprowadzić w sposób bezpieczny, komfortowy i skuteczny. Czasami zwykłe leczenie zachowawcze okazuje się niewystarczające, a interwencja chirurgiczna staje się konieczna. Może to być usunięcie zębów zatrzymanych, takich jak ósemki, resekcja wierzchołków korzeni zębów, czy przygotowanie kości do leczenia implantologicznego. W chirurgii stomatologicznej zajmujemy się również usuwaniem zmian patologicznych, takich jak torbiele, oraz korekcją wad zgryzu czy rekonstrukcją tkanek. Każdy zabieg poprzedza dokładna konsultacja. W trakcie wizyty lekarz ocenia stan zdrowia jamy ustnej, analizuje zdjęcia RTG lub tomografię komputerową i omawia plan leczenia z pacjentem. Wszelkie procedury są przeprowadzane w znieczuleniu miejscowym, co sprawia, że są całkowicie bezbolesne. Dla pacjentów bardziej wymagających pod kątem komfortu oferujemy również sedację, która pomaga zrelaksować się podczas zabiegu. Wielu pacjentów obawia się chirurgii stomatologicznej, jednak w rzeczywistości jest to często kluczowy krok do rozwiązania problemów zdrowotnych, bólowych i estetycznych. Dzięki precyzyjnemu podejściu i zaawansowanemu sprzętowi, leczenie przebiega sprawnie, a proces gojenia jest możliwie jak najszybszy. Po zabiegu pacjent otrzymuje szczegółowe instrukcje, jak dbać o jamę ustną, aby zapobiec powikłaniom i zapewnić sobie komfort w okresie rekonwalescencji. W naszej klinice stawiamy na profesjonalizm i troskę o pacjenta. Zespół doświadczonych chirurgów zadba o to, by każdy zabieg był przeprowadzony z najwyższą precyzją i w przyjaznej atmosferze. Chirurgia stomatologiczna to krok w stronę zdrowego, pełnego uśmiechu, który zapewni Ci pewność siebie i komfort każdego dnia. Nie zwlekaj – skontaktuj się z nami i umów na konsultację. Razem znajdziemy najlepsze rozwiązanie dla Twojego zdrowia i dobrego samopoczucia.",
  },
  {
    title: "PROTETYKA",
    description: "Precyzyjne odbudowy protetyczne.",
    modalText:
      "Protetyka stomatologiczna - przywracamy Twój uśmiech Protetyka stomatologiczna to dziedzina, która pozwala odbudować brakujące lub uszkodzone zęby, przywracając estetykę, funkcjonalność oraz komfort życia. Niezależnie od tego, czy straciłeś pojedynczy ząb, kilka zębów, czy nawet wszystkie – nowoczesne rozwiązania protetyczne mogą pomóc Ci znów cieszyć się pełnym i zdrowym uśmiechem. Utrata zębów to nie tylko problem estetyczny. Braki w uzębieniu mogą prowadzić do trudności z jedzeniem, mówieniem, a także wpływać na układ żucia i zdrowie całego organizmu. Protetyka oferuje szeroką gamę rozwiązań, które są dopasowane do indywidualnych potrzeb pacjenta. Mogą to być korony, mosty, protezy częściowe i całkowite, a także zaawansowane rekonstrukcje na implantach. Proces leczenia rozpoczyna się od konsultacji i diagnostyki, podczas której lekarz dokładnie ocenia stan jamy ustnej i omawia możliwości leczenia. Wszystkie prace protetyczne są precyzyjnie projektowane i wykonywane z wykorzystaniem nowoczesnych technologii, takich jak skanery cyfrowe czy frezarki CAD/CAM. Dzięki temu uzyskujemy idealne dopasowanie i estetykę, która nie różni się od naturalnych zębów. Korony i mosty protetyczne pozwalają odbudować uszkodzone lub brakujące zęby, zachowując ich naturalny wygląd i funkcję. Protezy częściowe i całkowite to wygodne rozwiązanie dla osób z większymi brakami w uzębieniu, które zapewniają stabilność i komfort noszenia. Dzięki możliwości osadzenia protez na implantach, możesz zapomnieć o problemach związanych z ich przemieszczaniem się. W protetyce stomatologicznej liczy się nie tylko technologia, ale także indywidualne podejście do każdego pacjenta. W naszej klinice stawiamy na współpracę z pacjentem, aby zrozumieć jego oczekiwania i wspólnie osiągnąć najlepszy efekt. Precyzja, estetyka i trwałość to nasze priorytety. Jeśli braki w uzębieniu wpływają na Twoje codzienne życie, nie zwlekaj. Protetyka stomatologiczna to szansa na nowy początek – pełen uśmiech, pewność siebie i komfort każdego dnia. Skontaktuj się z nami i dowiedz się, jakie rozwiązanie będzie dla Ciebie najlepsze. Razem zadbamy o Twój uśmiech!",
  },
  {
    title: "STOMATOLOGIA ZACHOWAWCZA",
    description: "Leczenie próchnicy zębów",
    modalText:
      "Stomatologia zachowawcza - ochrona zdrowia Twoich zębów. Stomatologia zachowawcza to fundament codziennej opieki stomatologicznej, skupiający się na profilaktyce, leczeniu próchnicy i przywracaniu zdrowia zębów. Dzięki nowoczesnym metodom i materiałom, leczenie jest dziś skuteczne, bezpieczne i komfortowe, a zęby zachowują swoją funkcjonalność i estetykę na długie lata. Próchnica to jedna z najczęstszych chorób dotykających zęby, ale odpowiednio wczesna diagnoza pozwala skutecznie jej zapobiegać i leczyć. W stomatologii zachowawczej kluczowym elementem jest regularna profilaktyka – przeglądy stomatologiczne, profesjonalna higienizacja oraz edukacja pacjentów w zakresie właściwej higieny jamy ustnej. Gdy dochodzi do powstania ubytku, celem leczenia jest jego dokładne oczyszczenie i odbudowa struktury zęba przy użyciu trwałych, estetycznych materiałów. Nowoczesne wypełnienia światłoutwardzalne doskonale imitują naturalny wygląd zębów, są wytrzymałe i odporne na codzienne obciążenia. Dzięki temu leczone zęby nie tylko są zdrowe, ale także wyglądają naturalnie. Stomatologia zachowawcza obejmuje również leczenie nadwrażliwości zębów, które może znacząco obniżać komfort życia. Specjalistyczne preparaty i zabiegi wzmacniają szkliwo i chronią zęby przed działaniem bodźców termicznych, chemicznych czy mechanicznych. Jednym z najważniejszych celów stomatologii zachowawczej jest zapobieganie rozwojowi poważniejszych problemów, takich jak konieczność leczenia kanałowego czy ekstrakcji. Regularne wizyty kontrolne, które zaleca się odbywać co najmniej dwa razy w roku, pozwalają na wczesne wykrycie i skuteczne leczenie zmian próchnicowych. W naszej klinice stawiamy na indywidualne podejście do każdego pacjenta. Wykorzystujemy nowoczesne technologie diagnostyczne, dzięki którym możemy dokładnie ocenić stan jamy ustnej, oraz zaawansowane materiały, które gwarantują trwałość i estetykę wypełnień. Dbamy o to, aby każda wizyta była komfortowa, a leczenie przebiegało w przyjaznej atmosferze. Zdrowe zęby to nie tylko piękny uśmiech, ale także lepsza jakość życia. Nie czekaj, aż drobne problemy staną się poważnym wyzwaniem – umów się na wizytę i zadbaj o zdrowie swoich zębów już dziś. Stomatologia zachowawcza to prosty krok do długotrwałego zdrowia i pewności siebie!",
  },
  {
    title: "ORTODONCJA",
    description: "Perfekcyjny prosty uśmiech",
    modalText:
      "Ortodoncja nakładkowa - proste zęby w komfortowy sposób Ortodoncja nakładkowa to nowoczesne podejście do prostowania zębów, które łączy w sobie skuteczność tradycyjnego leczenia ortodontycznego z komfortem i dyskrecją. Dzięki specjalnym przezroczystym nakładkom możesz uzyskać idealny uśmiech bez konieczności stosowania widocznych aparatów stałych. To rozwiązanie idealne dla osób ceniących sobie estetykę i wygodę na co dzień. Nakładki ortodontyczne, często nazywane alignerami, są wykonywane indywidualnie dla każdego pacjenta na podstawie szczegółowego planu leczenia. Proces rozpoczyna się od konsultacji, podczas której lekarz ocenia stan uzębienia, wykonuje skany 3D lub wyciski, a następnie opracowuje cyfrowy plan korekty zębów. Na tej podstawie tworzy się serię nakładek, które delikatnie przesuwają zęby do pożądanej pozycji. Leczenie nakładkami ortodontycznymi jest niezwykle wygodne. Pacjent samodzielnie zmienia nakładki co około 1–2 tygodnie, zgodnie z zaleceniami lekarza. Nakładki są zdejmowalne, co pozwala na normalne jedzenie, picie oraz codzienną higienę jamy ustnej bez żadnych ograniczeń. Wystarczy nosić je przez około 20–22 godziny na dobę, aby osiągnąć zamierzony efekt. Ortodoncja nakładkowa to również rozwiązanie wyjątkowo dyskretne – przezroczyste nakładki są praktycznie niewidoczne, dzięki czemu możesz czuć się pewnie w każdej sytuacji, zarówno w pracy, jak i w towarzystwie. Ponadto nakładki wykonane są z gładkiego materiału, co eliminuje ryzyko podrażnień i dyskomfortu, które mogą występować przy tradycyjnych aparatach. Leczenie nakładkami jest skuteczne w wielu przypadkach – od drobnych korekt estetycznych po bardziej złożone wady zgryzu. Czas trwania terapii zależy od indywidualnych potrzeb i zakresu korekty, ale efekty są widoczne już po kilku miesiącach. W naszej klinice oferujemy pełne wsparcie na każdym etapie leczenia. Korzystamy z najnowszych technologii i współpracujemy z renomowanymi producentami alignerów, aby zapewnić Ci najlepsze rezultaty. Nasi specjaliści zadbają o to, aby Twój plan leczenia był dostosowany do Twoich potrzeb i oczekiwań. Jeśli marzysz o prostych zębach i pięknym uśmiechu bez kompromisów, ortodoncja nakładkowa jest dla Ciebie. Skontaktuj się z nami, umów na konsultację i przekonaj się, jak łatwo możesz poprawić swój uśmiech w nowoczesny, komfortowy sposób!",
  },
  {
    title: "DIAGNOSTYKA",
    description: "Punktowe zdjęcie RTG",
    modalText:
      "Diagnostyka stomatologiczna - fundament zdrowego uśmiechu Diagnostyka stomatologiczna to pierwszy krok w trosce o zdrowie zębów i dziąseł. Regularne badania pozwalają wykrywać nawet najmniejsze problemy w jamie ustnej, zanim staną się poważnym zagrożeniem dla Twojego zdrowia. Dzięki nowoczesnym technologiom możemy dziś dostrzec to, co jeszcze kilka lat temu było niewidoczne gołym okiem, i podjąć odpowiednie kroki, by zapobiec rozwojowi chorób. Podczas wizyty diagnostycznej lekarz stomatolog przeprowadza szczegółowy przegląd jamy ustnej, oceniając stan zębów, dziąseł oraz błon śluzowych. W razie potrzeby wykorzystujemy zaawansowane narzędzia, takie jak zdjęcia RTG, tomografia komputerowa czy kamery wewnątrzustne, które pozwalają zajrzeć w miejsca niedostępne dla standardowego badania. Dzięki temu możemy precyzyjnie planować leczenie i monitorować jego efekty. Diagnostyka stomatologiczna obejmuje wiele aspektów. Pozwala wykryć próchnicę, zanim stanie się bolesnym problemem, zidentyfikować choroby dziąseł, takie jak paradontoza, czy zbadać stan kości szczęki i żuchwy, co jest szczególnie ważne przed zabiegami implantologicznymi. Dodatkowo umożliwia rozpoznanie zmian patologicznych, takich jak torbiele czy inne nieprawidłowości, które wymagają interwencji chirurgicznej. Regularne wizyty kontrolne są niezwykle ważne, ponieważ wiele problemów w jamie ustnej rozwija się stopniowo i przez długi czas może przebiegać bezobjawowo. Wczesne wykrycie takich zmian pozwala uniknąć bólu, skomplikowanego leczenia i wyższych kosztów. Dlatego zaleca się, aby odwiedzać stomatologa co najmniej dwa razy w roku, nawet jeśli nie odczuwasz żadnych dolegliwości. W naszej klinice stawiamy na nowoczesne technologie i indywidualne podejście do każdego pacjenta. Wykorzystujemy zaawansowane urządzenia diagnostyczne, które gwarantują precyzję i bezpieczeństwo. Każda wizyta odbywa się w przyjaznej atmosferze, a nasz zespół zapewnia pełne wsparcie na każdym etapie leczenia. Dbaj o swoje zęby, zanim pojawią się problemy. Diagnostyka stomatologiczna to podstawa zdrowia Twojej jamy ustnej i pierwszy krok w kierunku pięknego uśmiechu. Umów się na wizytę i przekonaj się, jak łatwo można zadbać o swoje zdrowie!",
  },
  {
    title: "WYBIELANIE ZĘBÓW",
    description: "Zabieg estetyczny",
    modalText:
      "Wybielanie zębów - promienny uśmiech w zasięgu ręki Wybielanie zębów to jeden z najpopularniejszych zabiegów estetycznych w stomatologii, który pozwala odzyskać jasny i promienny uśmiech. Przebarwienia zębów mogą być wynikiem wielu czynników, takich jak picie kawy, herbaty, czerwonego wina, palenie tytoniu czy naturalne procesy starzenia. Dzięki nowoczesnym metodom wybielania zębów możesz skutecznie rozjaśnić swój uśmiech nawet o kilka odcieni, w sposób szybki, bezpieczny i komfortowy. Zabieg wybielania jest dostosowany do indywidualnych potrzeb pacjenta. Przed jego rozpoczęciem przeprowadzana jest konsultacja, podczas której oceniany jest stan zębów i dziąseł. To ważny etap, ponieważ skuteczne i bezpieczne wybielanie można przeprowadzić jedynie na zdrowych zębach, dlatego w razie potrzeby przed wybielaniem zaleca się wykonanie higienizacji oraz leczenia ewentualnych ubytków. W naszej klinice oferujemy profesjonalne wybielanie zębów, które odbywa się w dwóch głównych formach: **Wybielanie w gabinecie stomatologicznym** – to szybka i efektywna metoda, która daje natychmiastowe rezultaty. Wykorzystujemy specjalistyczne żele wybielające aktywowane światłem lampy. Cały zabieg trwa około godziny, a efekty są widoczne od razu po zakończeniu.  **Wybielanie domowe** – polega na stosowaniu indywidualnie dopasowanych nakładek wypełnionych żelem wybielającym. Pacjent używa ich w domu zgodnie z zaleceniami lekarza, zazwyczaj przez kilka godzin dziennie lub na noc. Proces ten jest bardziej stopniowy, ale równie skuteczny. Efekty wybielania są trwałe i mogą utrzymywać się przez wiele miesięcy, a nawet lat, w zależności od stylu życia i nawyków pacjenta. Aby zachować biel zębów na dłużej, zaleca się unikanie produktów barwiących, takich jak kawa, herbata, czy czerwone wino, oraz dbanie o regularną higienę jamy ustnej. Wybielanie zębów jest bezpieczne dla szkliwa, pod warunkiem że jest przeprowadzane pod kontrolą stomatologa. W naszej klinice korzystamy z nowoczesnych preparatów, które minimalizują ryzyko nadwrażliwości i zapewniają komfort podczas zabiegu. Twój uśmiech jest Twoją wizytówką – zadbaj o to, aby był jasny i pełen blasku. Skontaktuj się z nami, aby umówić się na konsultację i dowiedzieć się, która metoda wybielania będzie dla Ciebie najlepsza. Promienny uśmiech czeka na Ciebie!",
  },

  {
    title: "HIGIENIZACJA",
    description: "Gabinetowe oczyszczanie zębów z osadu i kamienia",
    modalText:
      "Higienizacja - zdrowy uśmiech zaczyna się od czystości Higienizacja to podstawowy zabieg profilaktyczny, który pozwala zadbać o zdrowie zębów i dziąseł, zapewniając świeżość i komfort w codziennym życiu. Regularne usuwanie osadu, kamienia nazębnego i przebarwień to nie tylko kwestia estetyki, ale przede wszystkim zdrowia jamy ustnej. Dzięki higienizacji możesz zapobiegać poważniejszym problemom stomatologicznym, takim jak próchnica, choroby dziąseł czy paradontoza. Proces higienizacji obejmuje kilka etapów, które razem tworzą kompleksową pielęgnację zębów. Zaczyna się od skalingu, czyli usuwania kamienia nazębnego za pomocą ultradźwięków. To kamień jest często główną przyczyną stanów zapalnych dziąseł i nieprzyjemnego zapachu z ust. Następnie wykonywany jest piaskowanie, które usuwa drobne osady i przebarwienia, przywracając zębom ich naturalną jasność. Ostatnim etapem jest polerowanie zębów, które sprawia, że stają się gładkie i mniej podatne na odkładanie się osadu, a także aplikacja preparatu z fluorem, wzmacniającego szkliwo. Higienizacja to zabieg szybki, bezbolesny i niezwykle skuteczny. Regularne wykonywanie higienizacji – zazwyczaj co 6 miesięcy – pozwala utrzymać zęby w doskonałym stanie i znacznie zmniejsza ryzyko poważniejszych problemów stomatologicznych. To także świetna okazja, aby skonsultować się z higienistką lub stomatologiem i dowiedzieć się więcej o codziennej pielęgnacji jamy ustnej. Zdrowie jamy ustnej to klucz do ogólnego zdrowia organizmu. Nagromadzony kamień nazębny może prowadzić do stanów zapalnych, które mają wpływ na zdrowie całego organizmu, w tym na serce czy układ oddechowy. Dlatego higienizacja to nie tylko inwestycja w piękny uśmiech, ale także w długofalowe zdrowie. W naszej klinice zabiegi higienizacyjne wykonujemy z najwyższą precyzją i dbałością o komfort pacjenta. Korzystamy z nowoczesnych urządzeń i preparatów, które gwarantują skuteczność i bezpieczeństwo zabiegu. Każdy pacjent otrzymuje także indywidualne wskazówki dotyczące higieny jamy ustnej, aby efekty higienizacji utrzymały się jak najdłużej. Zapraszamy na higienizację – to prosty krok do zdrowego i pięknego uśmiechu. Umów się na wizytę już dziś i ciesz się uczuciem świeżości i czystości na co dzień!",
  },
];

const Offer = () => (
  <div className="tiles-section">
    {tilesData.map((tile, index) => (
      <Tile
        key={index}
        title={tile.title}
        description={tile.description}
        modalText={tile.modalText}
        imagePath={tile.backgroundImagePath}
      />
    ))}
  </div>
);

export default Offer;
